src/main/java/oripa/domain/fold/Folder.java, src/main/java/oripa/domain/fold/OriFace.java, src/main/java/oripa/domain/fold/OrigamiModelFactory.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/persistent/doc/exporter/ExporterSVGFactory.java
Only works for the SVG export, which also groups the faces with their precreases. This could be very useful for people who are diagramming models.
=> Aux lines are collapsed into the folded model like precreases

.github/workflows/maven.yml
Closes #84 - runs `mvn package` and uploads the resulting `jar` file as an artifact.
=> Add Maven package action

src/main/java/oripa/domain/paint/InitialVisibilities.java, src/main/java/oripa/domain/paint/PaintContext.java, src/main/java/oripa/view/main/UIPanel.java, src/main/java/oripa/viewsetting/main/MainScreenSetting.java
=> Introduce initial value constants for visibilities.

src/main/java/oripa/domain/cptool/BisectorFactory.java, src/main/java/oripa/domain/cptool/SymmetricLineFactory.java, src/main/java/oripa/domain/paint/byvalue/SelectingVertexToDrawLine.java, src/main/java/oripa/domain/paint/line/SelectingSecondVertexForLine.java, src/main/java/oripa/domain/paint/vertical/SelectingLineForVertical.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/Segment.java, src/main/java/oripa/value/OriLine.java
=> Remove OriLine dependency from GeomUtil

src/main/java/oripa/view/main/MainFrame.java
=> Fix hint label initialization.

src/main/java/oripa/domain/cptool/Painter.java, src/main/java/oripa/domain/paint/PaintContext.java, src/main/java/oripa/domain/paint/PaintContextImpl.java, src/main/java/oripa/domain/paint/angle/AngleSnapPointFactory.java, src/main/java/oripa/domain/paint/core/SnapPointFactory.java, src/main/java/oripa/domain/paint/pbisec/PerpendicularBisectorSnapPointFactory.java, src/main/java/oripa/domain/paint/pbisec/PerpendicularBisectorSnapPointsSetterCommand.java, src/main/java/oripa/domain/paint/pbisec/SelectingFirstEndPoint.java, src/main/java/oripa/domain/paint/pbisec/SelectingSecondEndPoint.java, src/main/java/oripa/domain/paint/pbisec/SelectingSecondVertexForBisector.java, src/main/java/oripa/gui/bind/state/PaintBoundStateFactory.java, src/main/java/oripa/gui/presenter/creasepattern/AbstractGraphicMouseAction.java, src/main/java/oripa/gui/presenter/creasepattern/AngleSnapAction.java, src/main/java/oripa/gui/presenter/creasepattern/PerpendicularBisectorAction.java, src/main/java/oripa/gui/presenter/creasepattern/TwoPointBisectorAction.java, src/main/java/oripa/gui/presenter/creasepattern/geometry/NearestItemFinder.java, src/main/java/oripa/resource/ExplanationStringResource_en.java
=> Select ends of perpendicular bisector

src/main/java/oripa/domain/fold/Folder.java, src/main/java/oripa/domain/fold/subface/AnswerStack.java, src/main/java/oripa/domain/fold/subface/SubFace.java
=> Fast penetration detection

src/main/java/oripa/domain/fold/Folder.java, src/main/java/oripa/domain/fold/stackcond/StackConditionOf4Faces.java, src/main/java/oripa/util/Matrices.java
=> Tune up fold and add 4-face penetration detection

src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/domain/fold/subface/SubFacesFactory.java, src/test/java/oripa/domain/fold/subface/ParentFacesCollectorTest.java, src/test/java/oripa/domain/fold/subface/SplitFacesToSubFacesConverterTest.java, src/test/java/oripa/domain/fold/subface/SubFacesFactoryTest.java
Ambiguous words are replaced with more readable ones.
=> Refactor SubFace

src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/domain/fold/subface/ParentFacesCollector.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/domain/fold/subface/SubFacesFactory.java, src/main/java/oripa/util/Pair.java, src/test/java/oripa/domain/fold/subface/ParentFacesCollectorTest.java, src/test/java/oripa/domain/fold/subface/SubFacesFactoryTest.java
Refactoring and performance tuning.
=> Improve estimation

src/main/java/oripa/domain/fold/Folder.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/gui/view/main/UIPanel.java
Close #143 . Now my Smart Dragon is done in 10~15 seconds.
=> Fast algorithm for layer ordering

src/main/java/oripa/gui/presenter/main/FoldedModelWindowOpener.java, src/main/java/oripa/gui/view/main/DialogWhileFolding.java, src/main/java/oripa/gui/view/main/UIPanel.java, src/main/java/oripa/resource/InformationStringResource_en.java, src/main/java/oripa/resource/StringID.java
Shows a dialog while folding. Note that the computation continues even If user closes the dialog. I tried to implement cancellation but I failed.
If you want to stop the undergoing computation, close the dialog, and close the main window.
=> Modal dialog while folding

src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/subface/SubFace.java
For memory efficiency of preprocess for layer order enumeration.
=> Add counter to subface

src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModel.java, src/main/java/oripa/domain/fold/halfedge/TriangleFace.java, src/main/java/oripa/gui/view/estimation/FoldedModelScreen.java, src/main/java/oripa/gui/view/estimation/TriangleFace.java, src/main/java/oripa/gui/view/estimation/TriangleFaceFactory.java, src/main/java/oripa/gui/view/estimation/TriangleVertex.java
=> Refactor face triangulation

src/main/java/oripa/gui/view/estimation/DefaultColors.java, src/main/java/oripa/gui/view/estimation/EstimationResultUI.java, src/main/java/oripa/gui/view/estimation/FoldedModelScreen.java, src/main/java/oripa/gui/view/main/UIPanel.java, src/main/java/oripa/gui/view/util/TitledBorderFactory.java
Partial Implementation of #101 .
The color does not persist in file.
=> Color config on folded model

src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OriHalfedge.java, src/main/java/oripa/gui/view/estimation/FoldedModelScreen.java, src/main/java/oripa/gui/view/estimation/TriangleFace.java, src/main/java/oripa/gui/view/estimation/TriangleFaceFactory.java, src/main/java/oripa/gui/view/estimation/VertexColorMapFactory.java
=> Extract color from domain

src/main/java/oripa/gui/view/estimation/EstimationResultFrame.java, src/main/java/oripa/gui/view/estimation/EstimationResultUI.java, src/main/java/oripa/resource/ErrorStringResource_en.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java
As mentioned in #156.
Only regarding the `EstimationResultFrame` and `EstimationResultUI`
If I missed something please let me know.
=> Refactoring, adding String Resource usage

src/main/java/oripa/doc/OptionParser.java, src/main/java/oripa/doc/Property.java, src/main/java/oripa/gui/presenter/main/FoldedModelWindowOpener.java, src/main/java/oripa/gui/view/estimation/EstimationResultFrame.java, src/main/java/oripa/gui/view/estimation/EstimationResultUI.java, src/main/java/oripa/gui/view/main/MainFrame.java, src/main/java/oripa/gui/view/main/UIPanel.java, src/main/java/oripa/gui/view/util/ColorRGBPanel.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java, src/test/java/oripa/doc/OptionParserTest.java, src/test/java/oripa/doc/PropertyTest.java
Discussed in #101 .
Using memo field enables using colors with .fold .
=> Save color config in memo

src/main/java/oripa/application/main/PaintContextModification.java
=> Should not snap on grid points while grid is not visible after loading file.

src/main/java/oripa/domain/cptool/PseudoLineFactory.java, src/main/java/oripa/domain/paint/line/LineSnapPointFactory.java, src/main/java/oripa/domain/paint/line/LineSnapPointsSetterCommand.java, src/main/java/oripa/domain/paint/line/SelectingFirstEndPoint.java, src/main/java/oripa/domain/paint/line/SelectingSecondEndPoint.java, src/main/java/oripa/domain/paint/line/SelectingSecondVertexForLine.java, src/main/java/oripa/gui/presenter/creasepattern/TwoPointLineAction.java, src/main/java/oripa/resource/ExplanationStringResource_en.java
=> Snap when inputting line

src/main/java/oripa/gui/bind/ButtonFactory.java, src/main/java/oripa/gui/bind/PaintActionButtonFactory.java, src/main/java/oripa/gui/bind/binder/AbstractButtonBinder.java, src/main/java/oripa/gui/bind/binder/ApplicationStateButtonBinder.java, src/main/java/oripa/gui/bind/binder/Binder.java, src/main/java/oripa/gui/bind/binder/BinderInterface.java, src/main/java/oripa/gui/bind/binder/ViewChangeBinder.java, src/main/java/oripa/gui/view/main/MainFrame.java, src/main/java/oripa/gui/view/main/UIPanel.java, src/test/java/oripa/gui/bind/ButtonFactoryTest.java, src/test/java/oripa/gui/bind/binder/ButtonBinderTest.java
=> Remove cast from button creation

src/main/java/oripa/geom/RectangleDomain.java, src/main/java/oripa/gui/bind/state/PaintBoundStateFactory.java, src/main/java/oripa/gui/presenter/creasepattern/GraphicMouseAction.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/AbstractEnlarger.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/CenterOriginEnlarger.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/CornerOriginEnlarger.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/EnlargeLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/Enlarger.java, src/main/java/oripa/gui/view/estimation/FoldedModelScreen.java, src/main/java/oripa/gui/view/main/PainterScreen.java, src/main/java/oripa/gui/view/model/ModelViewScreen.java, src/main/java/oripa/gui/view/util/AffineCamera.java, src/main/java/oripa/gui/view/util/MouseUtility.java, src/main/java/oripa/resource/ExplanationStringResource_en.java
Ctrl + dragging offers center-origin scaling.
=> Add centering origin of scale

src/main/java/oripa/gui/presenter/creasepattern/AngleBisectorAction.java, src/main/java/oripa/gui/presenter/creasepattern/AngleSnapAction.java, src/main/java/oripa/gui/presenter/creasepattern/EditOutlineAction.java, src/main/java/oripa/gui/presenter/creasepattern/PerpendicularBisectorAction.java, src/main/java/oripa/gui/presenter/creasepattern/SymmetricalLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/TriangleSplitAction.java, src/main/java/oripa/gui/presenter/creasepattern/TwoPointLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/TwoPointSegmentAction.java, src/main/java/oripa/gui/presenter/creasepattern/VerticalLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/byvalue/AngleMeasuringAction.java, src/main/java/oripa/gui/presenter/creasepattern/byvalue/LengthMeasuringAction.java, src/main/java/oripa/gui/presenter/creasepattern/byvalue/LineByValueAction.java
Tells user the end of vertex selection by changing color of the vertex.
=> Response to vertex selection

src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java
=> Multi CP foldability check

src/main/java/oripa/application/main/OrigamiModelInteractiveBuilder.java, src/main/java/oripa/domain/fold/halfedge/ModelVerticesExtractor.java, src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModel.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/gui/presenter/main/FoldedModelWindowOpener.java, src/main/java/oripa/gui/view/estimation/EstimationResultFrameFactory.java, src/main/java/oripa/gui/view/foldability/FoldabilityCheckFrameFactory.java, src/main/java/oripa/gui/view/model/ModelViewFrame.java, src/main/java/oripa/gui/view/model/ModelViewFrameFactory.java, src/main/java/oripa/gui/view/model/ModelViewScreen.java, src/main/java/oripa/gui/view/util/ChildFrameManager.java, src/main/java/oripa/persistence/entity/FoldedModelFilterSelector.java, src/main/java/oripa/persistence/entity/OrigamiModelFilterSelector.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java, src/main/java/oripa/resource/StringResource_en.java
=> Multi CP x-ray

src/main/java/oripa/gui/presenter/main/FoldedModelWindowOpener.java, src/main/java/oripa/gui/view/estimation/EstimationResultFrame.java, src/main/java/oripa/gui/view/estimation/EstimationResultFrameFactory.java, src/main/java/oripa/gui/view/estimation/FoldedModelScreen.java, src/main/java/oripa/gui/view/main/MainFrame.java, src/main/java/oripa/gui/view/main/PainterScreen.java, src/main/java/oripa/gui/view/main/UIPanel.java, src/main/java/oripa/gui/view/model/ModelViewFrame.java, src/main/java/oripa/gui/view/model/ModelViewFrameFactory.java, src/main/java/oripa/gui/view/model/ModelViewScreen.java, src/main/java/oripa/gui/view/util/ListItemSelectionPanel.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java
=> Multi CP layer ordering

src/main/java/oripa/gui/bind/state/PaintBoundState.java, src/main/java/oripa/gui/bind/state/PaintBoundStateFactory.java, src/main/java/oripa/gui/view/main/MainFrame.java, src/main/java/oripa/resource/ExplanationStringResource_en.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java
=> Implement importing other crease pattern.

src/main/java/oripa/gui/presenter/creasepattern/enlarge/EnlargeLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/geometry/NearestItemFinder.java
Extract nearest point computation.
=> Refactor enlarge-line action

src/main/java/oripa/geom/GeomUtil.java
=> Fix bug of angle bisector for pi.

README.md, src/main/java/oripa/ORIPA.java, src/main/java/oripa/PluginLoader.java, src/main/java/oripa/gui/bind/state/BindingObjectFactoryFacade.java, src/main/java/oripa/gui/bind/state/PluginPaintBoundStateFactory.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java, src/main/java/oripa/gui/presenter/plugin/AbstractGraphicMouseActionPlugin.java, src/main/java/oripa/gui/presenter/plugin/GraphicMouseActionPlugin.java, src/main/java/oripa/gui/presenter/plugin/TestMouseActionPlugin.java, src/main/java/oripa/gui/view/main/UIPanelView.java, src/main/java/oripa/swing/view/main/UIPanel.java, src/main/resources/META-INF/services/oripa.gui.presenter.plugin.GraphicMouseActionPlugin
=> Mouse plugin

src/main/java/oripa/application/main/OrigamiModelInteractiveBuilder.java, src/main/java/oripa/domain/cptool/LineTypeOverwriter.java, src/main/java/oripa/domain/cptool/OverlappingLineExtractor.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/halfedge/ModelComponentExtractor.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/domain/paint/core/RaySnapPointFactory.java, src/main/java/oripa/domain/paint/core/SnapPointFactory.java, src/main/java/oripa/domain/paint/suggestion/TargetOriVertexFactory.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/gui/presenter/main/CheckerWindowOpener.java, src/main/java/oripa/gui/presenter/main/DocFileAccessPresenter.java, src/main/java/oripa/gui/presenter/main/ModelComputationFacade.java, src/test/java/oripa/domain/fold/foldability/ring/RingArrayListTest.java, src/test/java/oripa/domain/fold/halfedge/OriFaceTest.java
fix of #233 .
This bug is caused by wrong treatment of edge case when two parallel edges touch at those endpoints and don't share other parts.
=> layer ordering bug fix

src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/swing/view/estimation/FloatingRGB.java, src/main/java/oripa/swing/view/estimation/FoldedModelScreen.java, src/main/java/oripa/swing/view/estimation/TriangleFace.java, src/main/java/oripa/swing/view/estimation/VertexColorMapFactory.java
Replace with a RGB container class for readability.
=> Remove vector3d

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/OverlapRelationFactory.java, src/main/java/oripa/domain/fold/halfedge/ModelComponentExtractor.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/domain/fold/origeom/OverlapRelation.java, src/main/java/oripa/domain/fold/subface/SplitFacesToSubFacesConverter.java, src/main/java/oripa/domain/fold/subface/StackConditionAggregate.java, src/main/java/oripa/domain/fold/subface/SubFace.java
* faster initialization of the order of subfaces.
* remove penetration detection and add foldability test to deterministic estimation.
* refactoring.
=> Speed up layer ordering

src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java, src/main/java/oripa/domain/fold/halfedge/OriVertex.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/view/estimation/EstimationResultUIView.java, src/main/java/oripa/persistence/entity/FoldedModelFileAccessSupportSelector.java, src/main/java/oripa/persistence/entity/FoldedModelFileTypeKey.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelEntity.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelExporterFOLD.java, src/main/java/oripa/persistence/entity/loader/FoldedModelLoaderFOLD.java, src/main/java/oripa/persistence/foldformat/AssignmentConverter.java, src/main/java/oripa/persistence/foldformat/CreasePatternElementConverter.java, src/main/java/oripa/persistence/foldformat/FoldedModelElementConverter.java, src/main/java/oripa/persistence/foldformat/FoldedModelFOLDFormat.java, src/main/java/oripa/persistence/foldformat/Frame.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java
export (close #241) and import (not tested and disabled).
=> Model FOLD format

.classpath, README.md, pom.xml, src/main/java/oripa/ORIPA.java, src/main/java/oripa/application/main/DataFileAccess.java, src/main/java/oripa/cli/CommandLineFolder.java, src/main/java/oripa/cli/CommandLineInterfaceMain.java, src/main/java/oripa/cli/CreasePatternFileConverter.java, src/main/java/oripa/cli/FoldedModelImageExporter.java, src/main/java/oripa/persistence/foldformat/FoldedModelElementConverter.java
Implementation of #240.
close #240
=> Command line interface

src/main/java/oripa/persistence/foldformat/CreasePatternFOLDFormat.java, src/main/java/oripa/persistence/foldformat/FOLDFormat.java, src/main/java/oripa/persistence/foldformat/FoldedModelFOLDFormat.java, src/main/java/oripa/persistence/foldformat/Frame.java
=> Refactoring fold format

src/main/java/oripa/persistence/foldformat/FOLDFormat.java
=> FOLD inheritance bug fix

src/main/java/oripa/persistence/entity/exporter/FoldedModelExporterFOLD.java, src/main/java/oripa/persistence/entity/loader/FoldedModelLoaderFOLD.java, src/main/java/oripa/persistence/foldformat/FoldedModelElementConverter.java, src/main/java/oripa/persistence/foldformat/FoldedModelFOLDFormat.java
uses custom property of FOLD for easy computation.
=> Export/import precreases on folded model.

src/main/java/oripa/ORIPA.java, src/main/java/oripa/gui/presenter/creasepattern/EditOutlineActionWrapper.java, src/main/java/oripa/gui/presenter/creasepattern/byvalue/LengthMeasuringAction.java, src/main/java/oripa/gui/presenter/creasepattern/copypaste/CopyAndPasteActionWrapper.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java
=> Use binding object factory facade

src/main/java/oripa/application/estimation/FoldedModelSVGConfigFileAccess.java, src/main/java/oripa/file/FoldedModelSVGConfigReader.java, src/main/java/oripa/file/FoldedModelSVGConfigWriter.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/resource/Constants.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java
=> Save svg config

src/main/java/oripa/application/FileAccessService.java, src/main/java/oripa/application/estimation/EstimationResultFileAccess.java, src/main/java/oripa/application/main/DataFileAccess.java, src/main/java/oripa/application/model/OrigamiModelFileAccess.java, src/main/java/oripa/cli/CommandLineFolder.java, src/main/java/oripa/gui/presenter/file/FileAccessPresenter.java, src/main/java/oripa/gui/view/file/FileChooserView.java, src/main/java/oripa/gui/view/file/FileFilterProperty.java, src/main/java/oripa/persistence/dao/AbstractFileAccessSupportSelector.java, src/main/java/oripa/persistence/dao/AbstractFileDAO.java, src/main/java/oripa/persistence/entity/FoldedModelEntity.java, src/main/java/oripa/persistence/entity/FoldedModelFileAccessSupportSelector.java, src/main/java/oripa/persistence/entity/FoldedModelFileTypeKey.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelAllExporterFOLD.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelFOLDFactory.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelSingleExporterFOLD.java, src/main/java/oripa/swing/view/file/LoadingFileChooser.java, src/main/java/oripa/swing/view/file/SavingFileChooser.java
into saving selected state version and saving all states version.
=> Split folded model's FOLD exporter

src/main/java/oripa/domain/cptool/TypeForChange.java, src/main/java/oripa/domain/creasepattern/CreasePattern.java, src/main/java/oripa/domain/fold/SimpleFolder.java, src/main/java/oripa/domain/fold/foldability/BigLittleBigLemma.java, src/main/java/oripa/domain/fold/foldability/GeneralizedBigLittleBigLemma.java, src/main/java/oripa/domain/fold/foldability/MaekawaTheorem.java, src/main/java/oripa/domain/fold/foldability/VertexFoldability.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/halfedge/OriVertex.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModel.java, src/main/java/oripa/domain/suggestion/MaekawaTheoremSuggester.java, src/main/java/oripa/file/InitData.java, src/main/java/oripa/gui/presenter/creasepattern/CreasePatternGraphicDrawer.java, src/main/java/oripa/gui/presenter/creasepattern/CreasePatternViewContextImpl.java, src/main/java/oripa/gui/presenter/creasepattern/SelectLineAction.java, src/main/java/oripa/gui/presenter/main/ModelComputationFacade.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java, src/main/java/oripa/gui/view/main/InitialVisibilities.java, src/main/java/oripa/gui/view/main/UIPanelView.java, src/main/java/oripa/gui/viewsetting/main/PainterScreenSettingImpl.java, src/main/java/oripa/persistence/doc/exporter/ExporterCP.java, src/main/java/oripa/persistence/entity/exporter/CreasePatternExporterDXF.java, src/main/java/oripa/persistence/foldformat/AssignmentConverter.java, src/main/java/oripa/persistence/svg/CreasePatternToSvgConverter.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java, src/main/java/oripa/swing/drawer/java2d/CreasePatternElementSelector.java, src/main/java/oripa/swing/view/main/UIPanel.java, src/main/java/oripa/value/OriLine.java
=> Enable unassigned crease edit

src/main/java/oripa/domain/fold/AssignmentEnumerator.java, src/main/java/oripa/domain/fold/SubfacesOneTimeFactory.java, src/main/java/oripa/domain/fold/UnassignedModelFolder.java, src/main/java/oripa/domain/fold/UnassignedModelFolderFactory.java, src/main/java/oripa/domain/fold/foldability/VertexFoldability.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/halfedge/OriVertex.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/gui/presenter/main/ModelComputationFacade.java
=> Enable estimation for unassigned CP.

src/main/java/oripa/domain/fold/AssignmentEnumerator.java, src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/OverlapRelationFactory.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/halfedge/OriVertex.java, src/main/java/oripa/domain/fold/origeom/EstimationResult.java, src/main/java/oripa/domain/fold/origeom/OverlapRelation.java, src/main/java/oripa/domain/fold/stackcond/StackConditionOf4Faces.java
With bug fix of deterministic layer ordering.
A part of #260 .
=> Improve assignment enumerator

src/main/java/oripa/persistence/doc/loader/LoaderXML.java, src/main/java/oripa/resource/Version.java
=> Increase opx version

src/main/java/oripa/cli/CommandLineFolder.java, src/main/java/oripa/domain/fold/AssignedModelFolder.java, src/main/java/oripa/domain/fold/ErrorAllowedFolder.java, src/main/java/oripa/domain/fold/FolderFactory.java, src/main/java/oripa/domain/fold/halfedge/ModelType.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModel.java, src/main/java/oripa/gui/presenter/main/ModelComputationFacade.java
More readable and easy to extend.
=> Introduce factory pattern into Folder creation.

src/main/java/oripa/domain/cptool/LineTypeOverwriter.java, src/main/java/oripa/domain/cptool/OverlappingLineDivider.java, src/main/java/oripa/domain/fold/AssignedModelFolder.java, src/main/java/oripa/domain/fold/AssignmentEnumerator.java, src/main/java/oripa/domain/fold/ErrorAllowedFolder.java, src/main/java/oripa/domain/fold/FoldedModel.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/UnassignedModelFolder.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/presenter/estimation/SubfaceToOverlapRelationIndicesFactory.java, src/main/java/oripa/gui/view/estimation/EstimationResultUIView.java, src/main/java/oripa/persistence/entity/FoldedModelEntity.java, src/main/java/oripa/persistence/entity/loader/FoldedModelLoaderFOLD.java, src/main/java/oripa/swing/view/estimation/EstimationResultFrame.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/swing/view/estimation/FoldedModelScreen.java, src/main/java/oripa/swing/view/main/UIPanel.java, src/main/java/oripa/swing/view/util/ListItemSelectionPanel.java, src/main/java/oripa/swing/view/util/SimpleModalDialog.java, src/main/java/oripa/swing/view/util/SimpleModalWorker.java, src/main/java/oripa/util/collection/CollectionUtil.java
An idea for #267 .
Choose a subface and select the order on it. The choices of answer are reduced since the order on the subface is fixed.
=> State choices

src/main/java/oripa/gui/presenter/estimation/SubfaceToOverlapRelationIndicesFactory.java
=> Use atomic operation on filter construction.

pom.xml
For #206 .
Tested on Windows 11.
Maybe works on mac as well.
=> Add jpackage build.

.github/workflows/release.yml
=> Auto release when a tag is pushed

pom.xml
=> Fix release workflow.

.github/workflows/maven.yml, .github/workflows/release.yml
=> Resolve action warning

src/main/java/oripa/domain/paint/core/SnapPointFactory.java, src/main/java/oripa/domain/paint/pbisec/PerpendicularBisectorSnapPointFactory.java
=> snap point creation bug fix

src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/view/estimation/EstimationResultUIView.java, src/main/java/oripa/gui/view/util/ColorUtil.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelExporterSVG.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelSVGConfig.java, src/main/java/oripa/persistence/svg/SVGUtils.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java
=> Use the given colors in SVG output

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java
Following https://github.com/origamimagiro/flat-folder/discussions/20#discussioncomment-5552011
=> Add 4-face cover condition.

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/origeom/OverlapRelation.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/util/AtomicByteDenseMatrix.java
* Speed up setting conditions to subfaces.
* Parallelize transitivity check.
=> Small performance tuning on deterministic estimation

src/main/java/oripa/domain/fold/halfedge/OriHalfedge.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultFramePresenter.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java, src/main/java/oripa/gui/view/estimation/EstimationResultFrameView.java, src/main/java/oripa/resource/LabelStringResource_en.java, src/main/java/oripa/resource/StringID.java, src/main/java/oripa/swing/view/estimation/CoordinateConverter.java, src/main/java/oripa/swing/view/estimation/DistortionMethod.java, src/main/java/oripa/swing/view/estimation/EstimationResultFrame.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/swing/view/estimation/Face.java, src/main/java/oripa/swing/view/estimation/FaceFactory.java, src/main/java/oripa/swing/view/estimation/FoldedModelScreen.java, src/main/java/oripa/swing/view/estimation/OverlapRelationInterpolater.java, src/main/java/oripa/swing/view/estimation/TriangleFace.java, src/main/java/oripa/swing/view/estimation/TriangleFaceFactory.java, src/main/java/oripa/swing/view/estimation/TriangleVertex.java, src/main/java/oripa/swing/view/estimation/VertexDepthMapFactory.java
Shows layers by slightly moving vertices.
=> Distortion

src/main/java/oripa/swing/view/estimation/EstimationResultFrame.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/swing/view/estimation/FoldedModelScreen.java
=> Fix bugs on model switch action.

src/main/java/oripa/domain/cptool/BisectorFactory.java, src/main/java/oripa/geom/GeomUtil.java
More javadoc and some simplifications.
=> Refactor geom util

src/main/java/oripa/domain/cutmodel/CutModelOutlinesFactory.java, src/main/java/oripa/domain/paint/core/RaySnapPointFactory.java, src/main/java/oripa/domain/paint/core/SnapPointFactory.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/gui/presenter/creasepattern/geometry/NearestItemFinder.java
* narrow method call depth of overlap distinguishment.
* rename the methods and update javadoc.
=> Simplify GeomUtil

src/main/java/oripa/domain/creasepattern/CreasePattern.java, src/main/java/oripa/domain/creasepattern/CreasePatternImpl.java, src/main/java/oripa/domain/creasepattern/LineManager.java, src/main/java/oripa/domain/creasepattern/VerticesManager.java, src/main/java/oripa/domain/paint/BasicUndo.java, src/main/java/oripa/domain/paint/PaintContext.java, src/main/java/oripa/domain/paint/PaintContextImpl.java, src/main/java/oripa/domain/paint/byvalue/LineByValueCommand.java, src/main/java/oripa/domain/paint/copypaste/LinePasterCommand.java, src/main/java/oripa/domain/paint/core/PickedVerticesConnectionLineAdderCommand.java, src/main/java/oripa/domain/paint/deleteline/LineDeleterCommand.java, src/main/java/oripa/domain/paint/linetype/LineTypeChangerCommand.java, src/main/java/oripa/domain/paint/mirror/LineMirrorCommand.java, src/main/java/oripa/domain/paint/outline/OutlineEditerCommand.java, src/main/java/oripa/domain/paint/vertical/VerticalLineAdderCommand.java, src/main/java/oripa/geom/RectangleDomain.java, src/main/java/oripa/gui/presenter/creasepattern/AbstractGraphicMouseAction.java, src/main/java/oripa/gui/presenter/creasepattern/CreasePatternGraphicDrawer.java, src/main/java/oripa/gui/presenter/creasepattern/DeleteLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/LineTypeChangeAction.java, src/main/java/oripa/gui/presenter/creasepattern/RectangularSelectableAction.java, src/main/java/oripa/gui/presenter/creasepattern/SelectLineAction.java, src/main/java/oripa/gui/presenter/creasepattern/enlarge/EnlargeLineAction.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/presenter/main/PainterScreenPresenter.java, src/main/java/oripa/gui/view/main/PainterScreenView.java, src/main/java/oripa/resource/ExplanationStringResource_en.java, src/main/java/oripa/swing/view/main/PainterScreen.java, src/test/java/oripa/domain/creasepattern/VerticesManagerTest.java
With some improvements:
* Enable boundary selection on drag.
* Draw outer edges of grids.
* Refactoring.
close #304
=> Automatically refresh crease pattern object

src/main/java/oripa/domain/paint/core/AbstractActionState.java, src/main/java/oripa/domain/paint/core/PickingLine.java, src/main/java/oripa/domain/paint/core/PickingVertex.java, src/main/java/oripa/gui/presenter/creasepattern/AbstractGraphicMouseAction.java, src/main/java/oripa/gui/presenter/creasepattern/GraphicMouseAction.java, src/main/java/oripa/gui/presenter/creasepattern/copypaste/ChangeOriginAction.java, src/main/java/oripa/gui/presenter/creasepattern/copypaste/PasteAction.java, src/main/java/oripa/gui/presenter/plugin/AbstractGraphicMouseActionPlugin.java, src/main/java/oripa/gui/presenter/plugin/GraphicMouseActionPlugin.java, src/main/java/oripa/gui/presenter/plugin/TestMouseActionPlugin.java
Breaking compatibility. (Actually already broken by using reimplemented Vector2d.)
* Change interface and abstract class for plugin.
* Change abstract mouse action. 
*  Update javadoc.
=> Update plugin interface

src/main/java/oripa/domain/cptool/ElementRemover.java, src/main/java/oripa/domain/cptool/LineToLineAxiom.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/Line.java, src/main/java/oripa/geom/Segment.java, src/main/java/oripa/vecmath/Vector2d.java
Some utility methods are extracted as methods of value classes.
=> Extend values

src/main/java/oripa/domain/cptool/LineToLineAxiom.java, src/main/java/oripa/domain/paint/angle/SelectingEndPoint.java, src/main/java/oripa/domain/paint/line/SelectingFirstEndPoint.java, src/main/java/oripa/domain/paint/linetoline/SelectingFirstVertexForFoldLine.java, src/main/java/oripa/domain/paint/pbisec/SelectingFirstEndPoint.java, src/main/java/oripa/domain/paint/suggestion/SelectingEndPoint.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/Segment.java, src/main/java/oripa/util/MathUtil.java, src/test/java/oripa/domain/cptool/LineToLineAxiomTest.java
* The fold lines were fewer than expected in certain case.
* Couldn't undo when selecting the first vertex from snap points.
=> Line-to-line bug fix

src/main/java/oripa/domain/cptool/compgeom/AnalyticLine.java, src/main/java/oripa/domain/fold/foldability/KawasakiTheorem.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/Segment.java, src/main/java/oripa/util/MathUtil.java, src/main/java/oripa/vecmath/Vector2d.java, src/test/java/oripa/domain/cptool/LineToLineAxiomTest.java, src/test/java/oripa/domain/suggestion/KawasakiTheoremSuggesterTest.java
* Fix circular dependency between `MathUtil` and `Vector2d`.
* Move `angleOf()` to `Vector2d` as `ownAngle()`.
* Add `areRadianEqual()`.
* Update javadoc.
=> Refactor math util

src/main/java/oripa/domain/fold/halfedge/ModelComponentExtractor.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/domain/fold/origeom/OriGeomUtil.java, src/main/java/oripa/domain/fold/subface/ParentFacesCollector.java, src/test/java/oripa/domain/fold/halfedge/OriFaceTest.java, src/test/java/oripa/domain/fold/subface/ParentFacesCollectorTest.java
* Rename `isOnFace*()` `includes*()`.
* Simplify `OriGeomUtil.isFaceOverlap()`.
=> Refactor OriFace

src/test/java/oripa/domain/cptool/RoratedLineFactoryTest.java, src/test/java/oripa/domain/cptool/TiledLineFactoryTest.java, src/test/java/oripa/domain/cptool/test/DefaultPaperFactory.java, src/test/java/oripa/domain/fold/subface/FacesToCreasePatternConverterTest.java, src/test/java/oripa/domain/fold/subface/ParentFacesCollectorTest.java, src/test/java/oripa/domain/fold/subface/SplitFacesToSubFacesConverterTest.java, src/test/java/oripa/domain/fold/subface/test/OriFaceFactoryForTest.java, src/test/java/oripa/domain/paint/angle/AngleSnapInputStatesTest.java, src/test/java/oripa/domain/paint/line/LineInputStatesTest.java, src/test/java/oripa/domain/paint/linetoline/LineToLineInputStatesTest.java, src/test/java/oripa/domain/paint/pbisec/PBisecInputStatesTest.java, src/test/java/oripa/domain/paint/segment/SegmentInputStatesTest.java, src/test/java/oripa/domain/paint/suggestion/SuggestionInputStatesTest.java, src/test/java/oripa/domain/paint/test/InputStatesTestBase.java, src/test/java/oripa/geom/RectangleDomainTestWithXShapeLines.java, src/test/java/oripa/geom/test/TestCreasePatternFactory.java
Tests of input states. Not for all inputs but for those with relatively complex action.
=> Paint state test

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/halfedge/OriEdge.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/swing/view/main/UIPanel.java, src/main/java/oripa/swing/view/util/SimpleModalWorker.java, src/main/java/oripa/util/collection/CollectionUtil.java
With bug fix on search order sort.
=> Fix fold error handling

src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java
=> Increase face angle limit.

src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/condfac/FaceIndicesOnHalfEdgeFactory.java, src/main/java/oripa/domain/fold/condfac/OverlappingFaceIndexIntersectionFactory.java, src/main/java/oripa/domain/fold/condfac/StackConditionFactoryFacade.java, src/main/java/oripa/domain/fold/condfac/StackConditionOf4FaceFactory.java
=> Speed up condfac

src/main/java/oripa/renderer/estimation/CoordinateConverter.java, src/main/java/oripa/renderer/estimation/DistortionFacade.java, src/main/java/oripa/renderer/estimation/DistortionMethod.java, src/main/java/oripa/renderer/estimation/Face.java, src/main/java/oripa/renderer/estimation/FaceFactory.java, src/main/java/oripa/renderer/estimation/FloatingRGB.java, src/main/java/oripa/renderer/estimation/FoldedModelPixelRenderer.java, src/main/java/oripa/renderer/estimation/OverlapRelationInterpolater.java, src/main/java/oripa/renderer/estimation/TriangleFace.java, src/main/java/oripa/renderer/estimation/TriangleFaceFactory.java, src/main/java/oripa/renderer/estimation/TriangleVertex.java, src/main/java/oripa/renderer/estimation/VertexColorMapFactory.java, src/main/java/oripa/renderer/estimation/VertexDepthMapFactory.java, src/main/java/oripa/swing/drawer/java2d/PixelDrawer.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/swing/view/estimation/FoldedModelScreen.java, src/main/java/oripa/swing/view/util/AffineCamera.java
=> Extract folded model drawing

src/main/java/oripa/persistence/doc/loader/LoaderXML.java, src/main/java/oripa/persistence/xml/ElementLoader.java, src/main/java/oripa/persistence/xml/TypedXPath.java, src/main/java/oripa/persistence/xml/ValueNodeParser.java
=> Xpath wrapper

src/main/java/oripa/cli/CommandLineFolder.java, src/main/java/oripa/cli/CommandLineInterfaceMain.java
Equivalent to "First folded state" mode on GUI.
=> Add fold-any mode to CLI.

src/main/java/oripa/gui/presenter/main/ModelComputationFacade.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java
=> Clean up model computation.

src/main/java/oripa/cli/CommandLineInterfaceMain.java, src/main/java/oripa/cli/FoldedModelImageExporter.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OriHalfedge.java, src/main/java/oripa/domain/fold/halfedge/OriVertex.java, src/main/java/oripa/persistence/entity/exporter/FoldedModelPictureConfig.java, src/main/java/oripa/persistence/entity/loader/FoldedModelLoaderFOLD.java, src/main/java/oripa/persistence/foldformat/FoldedModelElementConverter.java, src/main/java/oripa/renderer/estimation/VertexColorMapFactory.java, src/main/java/oripa/renderer/estimation/VertexDepthMapFactory.java
=> Enable folded model picture output on CLI.

src/main/java/oripa/domain/cptool/PointToLinePointToLineAxiom.java, src/main/java/oripa/domain/cptool/RotatedLineFactory.java, src/main/java/oripa/domain/suggestion/FoldableLineAngleSuggester.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/Ray.java, src/main/java/oripa/gui/presenter/model/ModelViewScreenPresenter.java, src/main/java/oripa/renderer/estimation/CoordinateConverter.java, src/main/java/oripa/util/MathUtil.java, src/main/java/oripa/vecmath/Vector2d.java
* add rotate().
* add Vector2d to/from array conversion.
* add unitVector() factory method.
=> Refactor Vector2d.

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/EstimationResultRules.java
=> Remove 4 face cover constraint.

src/main/java/oripa/domain/cptool/AngleBisectorFactory.java, src/main/java/oripa/domain/cptool/LineToLineAxiom.java, src/main/java/oripa/domain/paint/vertical/VerticalLineAdderCommand.java, src/main/java/oripa/geom/GeomUtil.java, src/test/java/oripa/geom/GeomUtilTest.java
* Rename methods.
* Change angle bisector method to return the bisector line.
=> Refactor GeomUtil

src/main/java/oripa/domain/cptool/compgeom/PointAndOriLine.java, src/main/java/oripa/domain/cptool/compgeom/SharedPointsMap.java
Argument check showed existence of buggy method call.
=> Potential bug fix of meaningless point removal.

src/main/java/oripa/DataSet.java, src/main/java/oripa/application/FileAccessService.java, src/main/java/oripa/application/FileSelectionService.java, src/main/java/oripa/cli/CreasePatternFileConverter.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/presenter/file/FileAccessPresenter.java, src/main/java/oripa/gui/presenter/file/FileSelectionPresenter.java, src/main/java/oripa/gui/presenter/file/FileSelectionResult.java, src/main/java/oripa/gui/presenter/file/UserAction.java, src/main/java/oripa/gui/presenter/main/DocFileSelectionPresenter.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/presenter/model/ModelViewFramePresenter.java, src/main/java/oripa/persistence/dao/FileAccessSupportSelector.java, src/main/java/oripa/persistence/dao/FileDAO.java, src/main/java/oripa/persistence/doc/Doc.java, src/main/java/oripa/persistence/doc/loader/LoaderCP.java, src/main/java/oripa/persistence/doc/loader/LoaderDXF.java, src/main/java/oripa/persistence/doc/loader/LoaderFOLD.java, src/main/java/oripa/persistence/doc/loader/LoaderPDF.java, src/main/java/oripa/persistence/filetool/FileAccessSupport.java, src/main/java/oripa/persistence/filetool/MultiTypeAcceptableFileLoadingSupport.java, src/main/java/oripa/project/Project.java, src/test/java/oripa/persistence/dao/FileAccessSupportSelectorTest.java, src/test/java/oripa/persistence/dao/FileDAOTest.java, src/test/java/test/TestDataBuilder.java
* Add DAO tests.
* reorganize the main frame behavior related to file access.
* Extract file load and save responsibility from file access presenter.
=> Refactor persistence

src/main/java/oripa/ORIPA.java, src/main/java/oripa/application/estimation/FoldedModelFileAccessServiceFactory.java, src/main/java/oripa/gui/presenter/creasepattern/CreasePatternGraphicDrawer.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultComponentPresenterFactory.java, src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/presenter/estimation/FoldedModelFileSelectionPresenterFactory.java, src/main/java/oripa/gui/presenter/main/DocFileSelectionPresenter.java, src/main/java/oripa/gui/presenter/main/MainComponentPresenterFactory.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/presenter/main/SubFramePresenterFactory.java, src/main/java/oripa/gui/presenter/model/ModelViewComponentPresenterFactory.java, src/main/java/oripa/gui/presenter/model/ModelViewFramePresenter.java, src/main/java/oripa/gui/presenter/model/OrigamiModelFileSelectionPresenterFactory.java
=> Testable subframe presenters

src/main/java/oripa/application/FileAccessService.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/persistence/dao/DataAccessException.java, src/main/java/oripa/persistence/dao/DataAccessObject.java, src/main/java/oripa/persistence/dao/FileDAO.java, src/test/java/oripa/persistence/dao/FileDAOTest.java
To hide data access object's details.
=> Hide filetool exception

src/main/java/oripa/persistence/dao/FileSelectionSupportSelector.java, src/main/java/oripa/persistence/dao/FileType.java, src/main/java/oripa/persistence/doc/DocFileSelectionSupportSelectorFactory.java, src/main/java/oripa/persistence/entity/FoldedModelFileSelectionSupportSelectorFactory.java, src/main/java/oripa/persistence/entity/OrigamiModelFileSelectionSupportSelectorFactory.java, src/test/java/oripa/persistence/dao/FileSelectionSupportSelectorTest.java, src/test/java/oripa/persistence/doc/DocFileSelectionSupportSelectorFactoryTest.java, src/test/java/oripa/persistence/entity/FoldedModelFileSelectionSupportSelectorFactoryTest.java, src/test/java/oripa/persistence/entity/OrigamiModelFileSelectionSupportSelectorFactoryTest.java
* Reduce the reference to `FIleTypeProperty`.
* Consistent use of factoryl
=> Refactor selection support selector

build.gradle.kts, src/main/java/oripa/ORIPA.java, src/main/java/oripa/domain/paint/PaintContext.java, src/main/java/oripa/gui/presenter/file/FileSelectionPresenter.java, src/main/java/oripa/gui/presenter/file/FileSelectionResult.java, src/main/java/oripa/gui/presenter/main/DocFileSelectionPresenter.java, src/main/java/oripa/gui/presenter/main/FileAccessPresentationLogic.java, src/main/java/oripa/gui/presenter/main/MainComponentPresenterFactory.java, src/main/java/oripa/gui/presenter/main/MainFramePresentationLogic.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/view/main/MainFrameView.java, src/main/java/oripa/gui/view/util/ColorUtil.java, src/main/java/oripa/project/Project.java, src/main/java/oripa/swing/view/main/MainFrame.java, src/main/java/oripa/swing/view/main/UIPanel.java, src/test/java/oripa/gui/presenter/main/FileAccessPresentationLogicTest.java, src/test/java/oripa/gui/presenter/main/MainFramePresentationLogicTest.java, src/test/java/oripa/gui/presenter/main/MainFramePresenterTest.java
=> Test main presenter

src/main/java/oripa/gui/presenter/main/MainComponentPresenterFactory.java, src/main/java/oripa/gui/presenter/main/SubFramePresenterFactory.java, src/main/java/oripa/gui/presenter/main/UIPanelPresenter.java, src/test/java/oripa/gui/presenter/main/MainFramePresenterTest.java, src/test/java/oripa/gui/presenter/main/UIPanelPresenterTest.java
I noticed that code of registering handlers of mouse action buttons is boilerplate and less worth testing.
=> Add tests of model computation handling.

src/main/java/oripa/ORIPA.java, src/main/java/oripa/gui/presenter/main/MainFramePresenter.java, src/main/java/oripa/gui/presenter/main/logic/MainFramePresentationLogic.java, src/main/java/oripa/project/Project.java, src/test/java/oripa/gui/presenter/main/MainFramePresenterTest.java, src/test/java/oripa/gui/presenter/main/logic/FileAccessPresentationLogicTest.java, src/test/java/oripa/gui/presenter/main/logic/MainFramePresentationLogicTest.java, src/test/java/oripa/gui/presenter/main/logic/ModelIndexChangeListenerPutterTest.java
And bug fix: new data could not be saved.
=> Move main save config

src/main/java/oripa/domain/fold/SimpleFolder.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/domain/fold/subface/SplitFacesToSubFacesConverter.java, src/main/java/oripa/domain/fold/subface/SubFace.java, src/main/java/oripa/geom/Polygon.java, src/main/java/oripa/persistence/entity/loader/FoldedModelLoaderFOLD.java, src/main/java/oripa/persistence/foldformat/FoldedModelElementConverter.java, src/main/java/oripa/renderer/estimation/Distortion.java, src/main/java/oripa/renderer/estimation/FaceFactory.java, src/main/java/oripa/renderer/estimation/OverlapRelationInterpolater.java, src/test/java/oripa/domain/fold/halfedge/OriFaceTest.java, src/test/java/oripa/domain/fold/subface/SplitFacesToSubFacesConverterTest.java, src/test/java/oripa/domain/fold/subface/test/OriFaceFactoryForTest.java
Cover the side effect on computation time of precise calculation of face overlapping.
=> Speed up overlap relation interpolation

src/main/java/oripa/domain/cptool/ElementRemover.java, src/main/java/oripa/domain/fold/halfedge/OriFace.java, src/main/java/oripa/domain/fold/halfedge/OriFacesFactory.java, src/main/java/oripa/domain/fold/halfedge/OrigamiModelFactory.java, src/main/java/oripa/geom/Polygon.java, src/main/java/oripa/value/OriLine.java
* Fix element remover bug inserted by recent change.
* Reduce vertex of polygon of face.
=> Fix face creation

src/main/java/oripa/gui/presenter/estimation/EstimationResultUIPresenter.java, src/main/java/oripa/gui/presenter/estimation/logic/SubfaceToOverlapRelationIndicesFactory.java, src/main/java/oripa/gui/view/estimation/EstimationResultUIView.java, src/main/java/oripa/swing/view/estimation/EstimationResultUI.java, src/main/java/oripa/util/BitArray.java, src/main/java/oripa/util/BitSet.java, src/test/java/oripa/util/BitArrayTest.java
* Efficient sorting of parent faces
* Bit set for saving memory
=> Fast subface filtering

src/main/java/oripa/domain/cptool/PointsMerger.java, src/main/java/oripa/domain/fold/FolderFactory.java, src/main/java/oripa/domain/fold/subface/FacesToCreasePatternConverter.java, src/main/java/oripa/geom/GeomUtil.java, src/main/java/oripa/geom/TwoEarTriangulation.java, src/main/java/oripa/persistence/doc/exporter/ExporterFOLD.java, src/test/java/oripa/domain/fold/subface/FacesToCreasePatternConverterTest.java
wrong check of convexity after removing ear is fixed.
=> Fix ear clipping bug.

src/main/java/oripa/domain/fold/DeterministicLayerOrderEstimator.java, src/main/java/oripa/domain/fold/LayerOrderEnumerator.java, src/main/java/oripa/domain/fold/TransitivityChecker.java, src/main/java/oripa/gui/presenter/main/logic/ModelIndexChangeSupport.java
=> Add subface transitivity check on enumeration + fix paper domain bug.
